### ISSUE TITLE
Issue with typing directly into the Pikaday input

### ISSUE THREAD

**Issue by muudles** [nverba/pikaday-angular#8]
Hi, first of all thank you for the directive. 

I'm having issues with how the date is formatted after the user type directly into the input. This is also not working correctly on your demo page. 

For example: 
'01/02/2015' gets formatted to '01 January 0002'
'01 02 2014' and '01 05 2014' both gets formatted to '01 January 2014'

I was hoping to use ngBlur to capture the date before the directive tries to format it, but I can only capture the formatted version.

So now I can only use ngChange to capture all the changes and format it manually on ngBlur. 

If you could please fix this issue that would be most helpful!

**Comment by nverba** [comment]
Hi, 

This is my fault, I set the default moment.js format to `"ddd MMM D YYYY"`, to match the pikaday native `Wed Mar 18 2015` output.  This has a detrimental effect on the string inputs that the element will accept

__When using moment, it expects inputs to conform to the specified format.__

You can see your issue is the same on the [pikaday moment example page](http://dbushell.github.io/Pikaday/examples/moment), because it is not in the format moment expects. 

I'm going to change the default to something more sensible like "MM-DD-YYYY" in the next version bump. However, if you are using moment, you should be including the format attribute anyway. This will change depending on your locale. It's also good practice to communicate to your users the expected input format for dates to parse correctly.

For your example:

```
<!-- UK -->
<input pikaday="myPickerObject" format="DD-MM-YYYY">

<!-- US -->
<input pikaday="myPickerObject" format="MM-DD-YYYY">
```
Should do the trick...

I've set aside some time today to bring this all up to date with the latest pikaday. I will be looking into better locale management, including being able to specify input formats based on locale. I should probably better communicate the issues regarding accepted inputs when using moment in the readme.

I hope that clarifies things a little.

**Comment by nverba** [comment]
The latest release is now out, I elected to not supply any defaults to Pikaday in the end, relying on Pikaday & Moment's defaults instead. I've tried to clarify input/output formatting in the readme.

If you're still having issues retrieving the date, just ask.
